Vagrant.configure("2") do |config|

    config.vm.boot_timeout = 2700
    
    config.vm.define "winser2019" do |winser2019|
      winser2019.vm.box = "jborean93/WindowsServer2019"

      winser2019.winrm.port = 5986
      winser2019.winrm.transport = :ssl
      winser2019.winrm.ssl_peer_verification = false

    end
    config.vm.provider :libvirt do |l|
      l.nic_model_type = "e1000"
    end
  end
